site_name: MkLorum
site_url: https://example.com/
nav:
  - Home: index.md
  - Getting Started: starting.md
  - Back-end: backend.md
  - Front-end: frontend.md
  - Testing: testing.md
  - Documentation: documentation.md
  - Feature Requests: featurerequests.md
theme: readthedocs
